apiVersion: v1
kind: Pod
metadata:
  name: podsa
spec:
  serviceACcountName: podsa
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - "sh"
        - "-c"
        - "sleep 1000"
  